// Compiles contracts/LiluneToken.sol into src/liluneToken.js (ABI + bytecode).
// Run with `npm run compile:token` after changing the contract.
import { readFileSync, writeFileSync } from "node:fs";
import solc from "solc";

const source = readFileSync(new URL("../contracts/LiluneToken.sol", import.meta.url), "utf8");
const output = JSON.parse(
  solc.compile(
    JSON.stringify({
      language: "Solidity",
      sources: { "LiluneToken.sol": { content: source } },
      settings: {
        optimizer: { enabled: true, runs: 200 },
        evmVersion: "paris",
        outputSelection: { "*": { "*": ["abi", "evm.bytecode.object"] } },
      },
    }),
  ),
);
const errors = (output.errors || []).filter((error) => error.severity === "error");
if (errors.length) {
  console.error(errors.map((error) => error.formattedMessage).join("\n"));
  process.exit(1);
}
const contract = output.contracts["LiluneToken.sol"].LiluneToken;
writeFileSync(
  new URL("../src/liluneToken.js", import.meta.url),
  `// Generated by scripts/compile-token.mjs from contracts/LiluneToken.sol. Do not edit.\n` +
    `export const liluneTokenAbi = ${JSON.stringify(contract.abi)};\n` +
    `export const liluneTokenBytecode = "0x${contract.evm.bytecode.object}";\n`,
);
console.log(`LiluneToken compiled (${contract.evm.bytecode.object.length / 2} bytes)`);
